version: '3'
services:
  fullstack-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}  
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 5432:5432
  app:
    container_name: full-rest-api
    build: .
    volumes:
      - api:/usr/src/app/
    ports:
      - "4000:4000"
    depends_on:
      - fullstack-postgres
    environment:
      WAIT_HOSTS: ${DATABASE_HOST}:5432
volumes:
  api:
  database_postgres: