version: '3'
services:
  postgres_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}  
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 5432:5432
  # redis_database:
  #   image: redis:5.0.6-alpine 
  #   command: ["redis-server", "--appendonly", "yes"]
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  app:
    container_name: full-rest-api
    build: .
    volumes:
      - api:/usr/src/app/
    ports:
      - "4000:4000"
    depends_on:
      - postgres_database
      # - redis_database
    environment:
      WAIT_HOSTS: ${DATABASE_HOST}:5432
volumes:
  api:
  # redis_data: